# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 14:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name="Date de création de l'expérience")),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création du plan')),
                ('hauteur_helice', models.IntegerField(choices=[(65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100), (101, 101), (102, 102), (103, 103), (104, 104), (105, 105), (106, 106), (107, 107), (108, 108), (109, 109), (110, 110), (111, 111), (112, 112), (113, 113), (114, 114), (115, 115), (116, 116), (117, 117), (118, 118), (119, 119), (120, 120), (121, 121), (122, 122), (123, 123), (124, 124), (125, 125)], default=70, verbose_name="Hauteur de l'hélice (mm)")),
                ('hauteur_habitacle', models.IntegerField(choices=[(10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35)], default=25, verbose_name="Hauteur de l'habitacle (mm)")),
                ('hauteur_corps', models.IntegerField(choices=[(35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100), (101, 101), (102, 102), (103, 103), (104, 104), (105, 105), (106, 106), (107, 107), (108, 108), (109, 109), (110, 110), (111, 111), (112, 112), (113, 113), (114, 114), (115, 115), (116, 116), (117, 117), (118, 118), (119, 119), (120, 120), (121, 121), (122, 122), (123, 123), (124, 124), (125, 125)], default=70, verbose_name='Hauteur du corps (mm)')),
                ('largeur_totale', models.IntegerField(choices=[(40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65)], default=50, verbose_name='Largeur totale (mm)')),
                ('trombones', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1, verbose_name='Nombre de trombones')),
                ('repli', models.BooleanField(default=True, verbose_name="Repli en bout d'hélice")),
                ('corps_scotche', models.BooleanField(default=True, verbose_name='Corps scotché')),
                ('helices_scotchees', models.BooleanField(default=True, verbose_name='Hélices scotchées')),
                ('decalage_repli', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=5, verbose_name='Décalage du repli (mm)')),
                ('angle_repli', models.IntegerField(choices=[(70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100), (101, 101), (102, 102), (103, 103), (104, 104), (105, 105), (106, 106), (107, 107), (108, 108), (109, 109), (110, 110)], default=75, verbose_name='Angle du repli (°)')),
                ('couches_corps', models.IntegerField(choices=[(1, 1), (3, 3)], default=1, verbose_name='Corps en n couche repliées')),
                ('sens_rotation', models.IntegerField(choices=[(1, 'horaire'), (-1, 'anti-horaire')], default=1, verbose_name='Sens de rotation')),
                ('largeur_scotch', models.IntegerField(choices=[(19, 19)], default=19, verbose_name='Largeur de scotch (mm)')),
                ('imprimer_symboles', models.BooleanField(choices=[(True, 'Oui')], default=True, verbose_name='Imprimer les symboles')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.IntegerField(choices=[(0, 'non inscrit'), (1, 'élève atelier'), (2, 'prof atelier')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='variationAA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création de la variation')),
                ('param1', models.IntegerField(choices=[(0, "Hauteur de l'hélice (mm)"), (1, "Hauteur de l'habitacle (mm)"), (2, 'Hauteur du corps (mm)'), (3, 'Largeur totale (mm)'), (4, 'Nombre de trombones'), (5, 'Décalage du repli (mm)'), (6, 'Angle du repli (°)')], default=0, verbose_name='paramètre analogique 1')),
                ('param2', models.IntegerField(choices=[(0, "Hauteur de l'hélice (mm)"), (1, "Hauteur de l'habitacle (mm)"), (2, 'Hauteur du corps (mm)'), (3, 'Largeur totale (mm)'), (4, 'Nombre de trombones'), (5, 'Décalage du repli (mm)'), (6, 'Angle du repli (°)')], default=0, verbose_name='paramètre analogique 2')),
                ('val11', models.IntegerField(verbose_name='valeur 1 (1)')),
                ('val12', models.IntegerField(verbose_name='valeur 1 (2)')),
                ('val13', models.IntegerField(verbose_name='valeur 1 (3)')),
                ('val21', models.IntegerField(verbose_name='valeur 2 (1)')),
                ('val22', models.IntegerField(verbose_name='valeur 2 (2)')),
                ('val23', models.IntegerField(verbose_name='valeur 2 (3)')),
                ('val24', models.IntegerField(verbose_name='valeur 2 (4)')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'variation analogique/analogique',
                'verbose_name_plural': 'variations analogique/analogique',
            },
        ),
        migrations.CreateModel(
            name='variationBA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création de la variation')),
                ('param1', models.IntegerField(choices=[(0, "Repli en bout d'hélice"), (1, 'Corps scotché'), (2, 'Hélices scotchées'), (3, 'Corps en n couche repliées'), (4, 'Sens de rotation')], default=0, verbose_name='paramètre binaire 1')),
                ('param2', models.IntegerField(choices=[(0, "Repli en bout d'hélice"), (1, 'Corps scotché'), (2, 'Hélices scotchées'), (3, 'Corps en n couche repliées'), (4, 'Sens de rotation')], default=0, verbose_name='paramètre binaire 2')),
                ('param3', models.IntegerField(choices=[(0, "Hauteur de l'hélice (mm)"), (1, "Hauteur de l'habitacle (mm)"), (2, 'Hauteur du corps (mm)'), (3, 'Largeur totale (mm)'), (4, 'Nombre de trombones'), (5, 'Décalage du repli (mm)'), (6, 'Angle du repli (°)')], default=0, verbose_name='paramètre analogique')),
                ('val31', models.IntegerField(verbose_name='valeur 3 (1)')),
                ('val32', models.IntegerField(verbose_name='valeur 3 (3)')),
                ('val33', models.IntegerField(verbose_name='valeur 3 (3)')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'variation binaire/analogique',
                'verbose_name_plural': 'variations binaire/analogique',
            },
        ),
        migrations.AddField(
            model_name='experience',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.Plan'),
        ),
        migrations.AddField(
            model_name='experience',
            name='var1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.variationAA'),
        ),
        migrations.AddField(
            model_name='experience',
            name='var2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.variationBA'),
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together=set([('hauteur_helice', 'hauteur_habitacle', 'hauteur_corps', 'largeur_totale', 'trombones', 'repli', 'corps_scotche', 'helices_scotchees', 'decalage_repli', 'angle_repli', 'couches_corps', 'sens_rotation', 'largeur_scotch', 'imprimer_symboles')]),
        ),
    ]
