# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 15:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='variationBB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création de la variation')),
                ('param11', models.IntegerField(choices=[(0, "Repli en bout d'hélice"), (1, 'Corps scotché'), (2, 'Hélices scotchées'), (3, 'Corps en n couche repliées'), (4, 'Sens de rotation')], default=0, verbose_name='premier paramètre du premier groupe')),
                ('param12', models.IntegerField(choices=[(0, "Repli en bout d'hélice"), (1, 'Corps scotché'), (2, 'Hélices scotchées'), (3, 'Corps en n couche repliées'), (4, 'Sens de rotation')], default=0, verbose_name='deuxième paramètre du premier groupe')),
                ('param13', models.IntegerField(choices=[(0, "Repli en bout d'hélice"), (1, 'Corps scotché'), (2, 'Hélices scotchées'), (3, 'Corps en n couche repliées'), (4, 'Sens de rotation')], default=0, verbose_name='troisième paramètre du premier groupe')),
                ('param21', models.IntegerField(choices=[(0, "Repli en bout d'hélice"), (1, 'Corps scotché'), (2, 'Hélices scotchées'), (3, 'Corps en n couche repliées'), (4, 'Sens de rotation')], default=0, verbose_name='premier paramètre du deuxième groupe')),
                ('param22', models.IntegerField(choices=[(0, "Repli en bout d'hélice"), (1, 'Corps scotché'), (2, 'Hélices scotchées'), (3, 'Corps en n couche repliées'), (4, 'Sens de rotation')], default=0, verbose_name='deuxième paramètre du deuxième groupe')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'variation binaire/binaire',
                'verbose_name_plural': 'variations binaire/binaire',
            },
        ),
        migrations.AlterField(
            model_name='experience',
            name='var1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.variationAA', verbose_name='variantes analogique/analogique'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='var2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.variationBA', verbose_name='variantes binaire/analogique'),
        ),
        migrations.AddField(
            model_name='experience',
            name='var3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.variationBB', verbose_name='variantes binaire/binaire'),
        ),
    ]
