# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='HauteurHelice',
        ),
        migrations.AddField(
            model_name='plan',
            name='angle_repli',
            field=models.IntegerField(choices=[(70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100), (101, 101), (102, 102), (103, 103), (104, 104), (105, 105), (106, 106), (107, 107), (108, 108), (109, 109), (110, 110)], default=75, verbose_name='Angle du repli (°)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='corps_scotche',
            field=models.BooleanField(default=True, verbose_name='Corps scotché'),
        ),
        migrations.AddField(
            model_name='plan',
            name='couches_corps',
            field=models.IntegerField(choices=[(1, 1), (3, 3)], default=1, verbose_name='Corps en n couche repliées'),
        ),
        migrations.AddField(
            model_name='plan',
            name='decalage_repli',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=5, verbose_name='Décalage du repli (mm)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='hauteur_corps',
            field=models.IntegerField(choices=[(35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100), (101, 101), (102, 102), (103, 103), (104, 104), (105, 105), (106, 106), (107, 107), (108, 108), (109, 109), (110, 110), (111, 111), (112, 112), (113, 113), (114, 114), (115, 115), (116, 116), (117, 117), (118, 118), (119, 119), (120, 120), (121, 121), (122, 122), (123, 123), (124, 124), (125, 125)], default=70, verbose_name='Hauteur du corps (mm)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='hauteur_habitacle',
            field=models.IntegerField(choices=[(10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35)], default=25, verbose_name="Hauteur de l'habitacle (mm)"),
        ),
        migrations.AddField(
            model_name='plan',
            name='hauteur_helice',
            field=models.IntegerField(choices=[(65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100), (101, 101), (102, 102), (103, 103), (104, 104), (105, 105), (106, 106), (107, 107), (108, 108), (109, 109), (110, 110), (111, 111), (112, 112), (113, 113), (114, 114), (115, 115), (116, 116), (117, 117), (118, 118), (119, 119), (120, 120), (121, 121), (122, 122), (123, 123), (124, 124), (125, 125)], default=70, verbose_name="Hauteur de l'hélice (mm)"),
        ),
        migrations.AddField(
            model_name='plan',
            name='helices_scotchees',
            field=models.BooleanField(default=True, verbose_name='Hélices scotchées'),
        ),
        migrations.AddField(
            model_name='plan',
            name='imprimer_symboles',
            field=models.BooleanField(choices=[(True, 'Oui')], default=True, verbose_name='Imprimer les symboles'),
        ),
        migrations.AddField(
            model_name='plan',
            name='largeur_scotch',
            field=models.IntegerField(choices=[(19, 19)], default=19, verbose_name='Largeur de scotch (mm)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='largeur_totale',
            field=models.IntegerField(choices=[(30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55)], default=50, verbose_name='Largeur totale (mm)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='repli',
            field=models.BooleanField(default=True, verbose_name="Repli en bout d'hélice"),
        ),
        migrations.AddField(
            model_name='plan',
            name='sens_rotation',
            field=models.IntegerField(choices=[(1, 'horaire'), (-1, 'anti-horaire')], default=1, verbose_name='Sens de rotation'),
        ),
        migrations.AddField(
            model_name='plan',
            name='trombones',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1, verbose_name='Nombre de trombones'),
        ),
    ]
