# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_experienceaa'),
    ]

    operations = [
        migrations.CreateModel(
            name='variationAA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param1', models.IntegerField(choices=[(0, "Hauteur de l'hélice (mm)"), (1, "Hauteur de l'habitacle (mm)"), (2, 'Hauteur du corps (mm)'), (3, 'Largeur totale (mm)'), (4, 'Nombre de trombones'), (5, 'Décalage du repli (mm)'), (6, 'Angle du repli (°)')], default=0, verbose_name='paramètre analogique 1')),
                ('param2', models.IntegerField(choices=[(0, "Hauteur de l'hélice (mm)"), (1, "Hauteur de l'habitacle (mm)"), (2, 'Hauteur du corps (mm)'), (3, 'Largeur totale (mm)'), (4, 'Nombre de trombones'), (5, 'Décalage du repli (mm)'), (6, 'Angle du repli (°)')], default=0, verbose_name='paramètre analogique 2')),
                ('val11', models.IntegerField(verbose_name='valeur 1 (1)')),
                ('val12', models.IntegerField(verbose_name='valeur 1 (2)')),
                ('val13', models.IntegerField(verbose_name='valeur 1 (3)')),
                ('val21', models.IntegerField(verbose_name='valeur 2 (1)')),
                ('val22', models.IntegerField(verbose_name='valeur 2 (2)')),
                ('val23', models.IntegerField(verbose_name='valeur 2 (3)')),
                ('val24', models.IntegerField(verbose_name='valeur 2 (4)')),
            ],
            options={
                'verbose_name': 'variation analogique/analogique',
                'verbose_name_plural': 'variations analogique/analogique',
            },
        ),
        migrations.DeleteModel(
            name='experienceAA',
        ),
    ]
